### ISSUE TITLE
Be sure to add a test script that upgrades the implementation of the proxy contract.

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/Tms-contract#4]
**Describe the bug**
I heard that you chose to deploy this contract in a proxy pattern. 
If this is a proxy pattern,
and if we want to use it at production level, we need to make sure that the implementation of the proxy is upgradeable.

**Configuration**
- Severity : Informational (but Required)

**Impact*
If an incident occurs, and if it cannot be upgraded or paused, there is nothing we can do

**Recommendation**
Add a test script that upgrades  the implementation of the proxy contract.
`upgradeTo`, `upgradeToAndCall`, `changeAdmin` needs to be tested.

**Comment by shivtokamak** [comment]
Fixed , pls check

**Comment by usgeeus** [comment]
@shivtokamak 
I checked your test code, thanks.
But why use the proxy pattern if nothing is stored as contract states???

**Comment by shivtokamak** [comment]
It was to add new functions for future like senderc721 ,etc

**Comment by usgeeus** [comment]
Then you can just deploy a new contract, I'm asking because I'm not sure there's enough motivation to use a proxy pattern. Proxy pattern delegateCalls functions using more gas.

This is not a contract security issue, so if you decided to use the proxy pattern anyway, then you can close this issue.

**Comment by Zena-park** [comment]
In the emergency cases such as when funds are locked(If someone accidentally sends funds or there is a logic error.), it is safe to use a proxy pattern.

**Comment by shivtokamak** [comment]
Please check, added rescue erc20 function

**Comment by usgeeus** [comment]
Thanks
