### ISSUE TITLE
Why do you use IERC20Upgradeable interface?

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/Tms-contract#6]
**Describe the bug**
Is there a specific purpose for using the IERC20Upgradeable interface?

**Configuration**
- Severity : Question

**Comment by usgeeus** [comment]
Also you imported ERC20.sol, but ERC20.sol is not used.

**Comment by bayram98** [comment]
@usgeeus 

The reason why I wanted to use IERC20Upgradeable is because I wanted to use the upgradable contracts. I think that upgradable contract logic would better to maintain the contracts production.

**Comment by bayram98** [comment]
> Also you imported ERC20.sol, but ERC20.sol is not used.

I think ERC.sol is not necessary. So I will be removing then on my new Pr.

https://github.com/tokamak-network/Tms-contract/pull/15

**Comment by usgeeus** [comment]
> @usgeeus
> 
> The reason why I wanted to use IERC20Upgradeable is because I wanted to use the upgradable contracts. I think that upgradable contract logic would better to maintain the contracts production.

What does it have to do with the contract being upgradable and declaring the type of the token as IERC20Upgradeable?

**Comment by Shivansh070707** [comment]
Hey , I think both IERC20upgradable and IERC20 interfaces are similar so we can use any of them
